### PR TITLE
SBP Milestone Review - 1

### PR DESCRIPTION
**Pull request by hbulgarini**
# SBP Milestone Review #1

- The setup of the Cumulus pallets appears to be correct and does not require any changes.

- Some changes were suggested regarding the organization of the code where certain configurations could be moved to different files.

- It is recommended to review the configuration of the `xcm_config` file as it seems to be default and might not cater to the needs of the parachain.

- Avoid using the `pallet_nicks` as it should only be used for demos (it does not even have benchmarking).

I definitely believe that for the next milestone, the parachain code needs to be moved to its own repository, thus having one repository for the solo chain and another for the parachain. Even though the setup is correct, the runtime contains too many configured pallets making it confusing to read at times. On the other hand, this would also make the reading and configuration of the node files (service.rs, command.rs, etc) easier. Nonetheless, it's noticeable that a deep analysis of the node's operation has been conducted, resulting in a well-configured system.

### CODE REVIEW

**Comment by okalenyk** [comment]
Hi @hbulgarini! Thanks for the review! What's the procedure for addressing changes requested in the review? Should we create a PR to your fork repo adding changes directly to the review?

**Comment by hbulgarini** [comment]
> [okalenyk](/okalenyk)

Hey Oleh! just address the comments on your repo following your processes and point them out in the next milestone review :)

**Comment by okalenyk** [comment]
Addressing review requests - [link to the PR for reference](https://github.com/sctllabs/societal-node/pull/155)

**Comment by okalenyk** [comment]
Closing the PR since all of the review requests have been addressed - see conversation above.

**Pull request closed without merging**
